#ifndef DECL_H  
#define DECL_H

enum tokens{
   CAR,INT,PROGRAMA,
   RETORNE,LEIA,ESCREVA,NOVALINHA,
   SE, ENTAO,SENAO,ENQUANTO,EXECUTE,PV,
   AP,FP,ATRIB,EQUAL,DIF,V,MAIOR,MENOR,
   MAIOREQUAL,MENOREQUAL,SUM,SUB,MUL,DIV,
   ID,NUM,EXCL,E,OU	
}; 

#endif
